project_id = "breakthebeat"

[functions.submit-registration]
verify_jwt = false

[functions.recover-registration]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.check-in]
verify_jwt = false
