alter table public.participants
add column photo_path text,
add column photo_uploaded_at timestamptz;

alter table public.participants
add constraint participants_photo_path_length
check (photo_path is null or char_length(photo_path) between 1 and 512);

create index participants_event_email_photo_idx
on public.participants(event_id, email_normalized, photo_path);

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'participant-photos',
  'participant-photos',
  false,
  2097152,
  array['image/jpeg']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table public.participant_photo_attempts (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index participant_photo_attempts_key_created_idx
on public.participant_photo_attempts(key_hash, created_at desc);

alter table public.participant_photo_attempts enable row level security;
revoke all on table public.participant_photo_attempts from public, anon, authenticated;

comment on column public.participants.photo_path is
'Private Supabase Storage path for the participant photo. Nullable for registrations created before photo collection became mandatory.';

comment on table public.participant_photo_attempts is
'Hashed identifiers used to rate-limit the public participant photo update flow.';
